"""first init

Revision ID: 0090e75a4125
Revises: e2f606b2fe3d
Create Date: 2025-06-09 15:45:55.143181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0090e75a4125'
down_revision: Union[str, None] = 'e2f606b2fe3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('additional_images', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'additional_images')
    # ### end Alembic commands ###
