"""first init

Revision ID: 0d9c0007c937
Revises: 812d70ae4f4b
Create Date: 2025-05-12 15:37:04.330122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d9c0007c937'
down_revision: Union[str, None] = '812d70ae4f4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add with default value to satisfy NOT NULL constraint
    op.add_column('carts', sa.Column('mrp_price', sa.Float(), nullable=False, server_default='0'))
    op.add_column('carts', sa.Column('discount', sa.Float(), nullable=False, server_default='0'))
    op.add_column('carts', sa.Column('final_price', sa.Float(), nullable=False, server_default='0'))

    # Remove server_default after values are set (optional step in a future migration)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carts', 'final_price')
    op.drop_column('carts', 'discount')
    op.drop_column('carts', 'mrp_price')
    # ### end Alembic commands ###
