"""first init

Revision ID: 382cfd90b69b
Revises: f8e000da8272
Create Date: 2025-06-03 06:21:12.085722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '382cfd90b69b'
down_revision: Union[str, None] = 'f8e000da8272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offline_orders', sa.Column('is_returned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offline_orders', 'is_returned')
    # ### end Alembic commands ###
