"""first init

Revision ID: 812d70ae4f4b
Revises: 8d92323a42e8
Create Date: 2025-05-12 12:33:17.420483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '812d70ae4f4b'
down_revision: Union[str, None] = '8d92323a42e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('session_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'session_id')
    # ### end Alembic commands ###
