"""first init

Revision ID: e2f606b2fe3d
Revises: 382cfd90b69b
Create Date: 2025-06-04 10:42:57.772872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f606b2fe3d'
down_revision: Union[str, None] = '382cfd90b69b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'reason')
    # ### end Alembic commands ###
